name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Configure git for private modules
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Setup SSH key access
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Install Protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: "3.x"

      - name: Install protoc-gen-go
        run: go get -u github.com/golang/protobuf/protoc-gen-go

      - name: Build Protocol Buffers
        run: protoc -I server/ server/*.proto --go_out=plugins=grpc:server

      - name: Build Code
        run: go build -v .
